import { jiraDBPrismaClient } from "@/lib/jira-prisma-client";
import { userDBPrismaClient } from "@/lib/user-prisma-client";
import { NextRequest, NextResponse } from "next/server";

// Do not cache endpoint result
export const revalidate = 0;

export async function GET(req: NextRequest) {
  await main();

  return NextResponse.json(
    { isSuccess: true },
    { headers: { "Cache-Control": "no-store" } }
  );
}

async function main() {
  const seederId = "0uL2Ayo6sx4isx4ef6bGp1QqsoLlrjD1";
  await userDBPrismaClient.user.upsert({
    where: { email: "seeder@gmail.com" },
    update: {},
    create: {
      email: "seeder@gmail.com",
      name: "seeder",
      emailVerified: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      id: seederId,
    },
  });
  let worksapce = await jiraDBPrismaClient.workspace.findFirst({
    where: {
      members: {
        some: {
          userId: seederId,
        },
      },
    },
  });

  if (!worksapce) {
    worksapce = await jiraDBPrismaClient.workspace.create({
      data: {
        name: "default",
        imageUrl: "",
        inviteCode: "",
        userId: seederId,
      },
    });
    await jiraDBPrismaClient.member.create({
      data: {
        userId: seederId,
        workspaceId: worksapce.id,
        role: "Admin",
      },
    });
  }

  const checkCanvas = await jiraDBPrismaClient.canvasProject.findMany({
    where: {
      isTemplate: true,
    },
  });

  if (checkCanvas.length === 0) {
    for (const project of canvasProjects) {
      await jiraDBPrismaClient.canvasProject.create({
        data: {
          userId: seederId,
          height: 900,
          width: 1200,
          workspaceId: worksapce.id,
          name: project.name,
          json: JSON.stringify(project.json),
          thumbnailUrl: project.thumbnail,
          isTemplate: true,
        },
      });
    }
  }
}

const canvasProjects = [
  {
    thumbnail:
      "https://dzfvd4zd81.ufs.sh/f/ZgqgVp1atChfDGqwFQxbJd1h9C5FxTpPY2rnyaOljqsU6iRo",
    name: "car sale",
    json: {
      version: "5.5.2",
      objects: [
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 175.5,
          top: -286.5,
          width: 900,
          height: 1200,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: {
            color: "rgba(0,0,0,0.8)",
            blur: 5,
            offsetX: 0,
            offsetY: 0,
            affectStroke: false,
            nonScaling: false,
          },
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          name: "clip",
          selectable: false,
          hasControls: false,
        },
        {
          type: "image",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 134.48361053,
          top: -284.77960154,
          width: 1920,
          height: 2339,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.512518,
          scaleY: 0.512518,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          selectable: true,
          hasControls: true,
          src: "https://utfs.io/f/b145a164-cc6a-43d5-9a41-18c082b25ad1-1mlhs8.jpg",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 94.53915324,
          top: -292.96890221,
          width: 400,
          height: 400,
          fill: "rgba(0,0,0,1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 2,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.75362509,
          scaleY: 3.04770639,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 0.3,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 301.35259139,
          top: 454.86494379,
          width: 534.9625079,
          height: 90.4,
          fill: "rgba(255, 255, 255, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.20410473,
          scaleY: 1.20410473,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 500,
          fontSize: 80,
          text: "CAR SALE",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 95.54142616,
          top: 587.97400988,
          width: 534.9625079,
          height: 90.4,
          fill: "rgba(255, 255, 255, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.04618206,
          scaleY: 2.04618206,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 700,
          fontSize: 80,
          text: "PROMO",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -148.44735856,
          top: -475.44136381,
          width: 300,
          height: 300,
          fill: "rgba(150, 186, 194, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.95526638,
          scaleY: 1.95526638,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 0.69,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 857.43124766,
          top: 701.28774822,
          width: 300,
          height: 300,
          fill: "rgba(150, 186, 194, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.95526638,
          scaleY: 1.95526638,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 0.69,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 394.52981132,
          top: -223.03314538,
          width: 804.6484375,
          height: 65.54,
          fill: "rgba(255, 255, 255, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.58354456,
          scaleY: 0.58354456,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial",
          fontWeight: 500,
          fontSize: 58,
          text: "www.website.com",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 513.50190638,
          top: -22.22143902,
          width: 300,
          height: 300,
          fill: "rgba(150, 186, 194, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.03818561,
          scaleY: 1.03818561,
          angle: 15.5411416,
          flipX: false,
          flipY: false,
          opacity: 0.69,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 547.98370009,
          top: 109.10048645,
          width: 186.71875,
          height: 90.4,
          fill: "rgba(253, 254, 255, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.06059575,
          scaleY: 1.06059575,
          angle: 15.5411416,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 700,
          fontSize: 80,
          text: "30%",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -41.66579243,
          top: 414.23641813,
          width: 400,
          height: 400,
          fill: "rgba(0, 0, 0, 0)",
          stroke: "rgba(255, 252, 252, 1)",
          strokeWidth: 13,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.03729394,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          selectable: true,
          hasControls: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.5.2",
        originX: "left",
        originY: "top",
        left: 175.5,
        top: -286.5,
        width: 900,
        height: 1200,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: {
          color: "rgba(0,0,0,0.8)",
          blur: 5,
          offsetX: 0,
          offsetY: 0,
          affectStroke: false,
          nonScaling: false,
        },
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: true,
        hasControls: true,
      },
    },
  },
  {
    thumbnail:
      "https://dzfvd4zd81.ufs.sh/f/ZgqgVp1atChfUYakDtEhuHnKyNIPXbOWze9pVasM7AvdrECL",
    name: "coming soon",
    json: {
      version: "5.5.2",
      objects: [
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 175.5,
          top: -286.5,
          width: 900,
          height: 1200,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: {
            color: "rgba(0,0,0,0.8)",
            blur: 5,
            offsetX: 0,
            offsetY: 0,
            affectStroke: false,
            nonScaling: false,
          },
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          name: "clip",
          selectable: false,
          hasControls: false,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 542.44098913,
          top: -751.94941926,
          width: 300,
          height: 300,
          fill: "rgba(239, 185, 185, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.31712127,
          scaleY: 3.31712127,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 86.7253306,
          top: 1.17957223,
          width: 300,
          height: 300,
          fill: "rgba(168, 129, 106, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.28546147,
          scaleY: 3.0284943,
          angle: 32.17844516,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -98.15571418,
          top: 171.61322274,
          width: 300,
          height: 300,
          fill: "rgba(0, 0, 0, 0)",
          stroke: "rgba(122, 94, 78, 1)",
          strokeWidth: 5,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.87708757,
          scaleY: 3.0284943,
          angle: 32.17844516,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 355.30538269,
          top: 130.68053177,
          width: 315.5859375,
          height: 195.264,
          fill: "rgba(0, 0, 0, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.78137457,
          scaleY: 1.78137457,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Palatino",
          fontWeight: 500,
          fontSize: 80,
          text: "Coming Soon",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.5.2",
        originX: "left",
        originY: "top",
        left: 175.5,
        top: -286.5,
        width: 900,
        height: 1200,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: {
          color: "rgba(0,0,0,0.8)",
          blur: 5,
          offsetX: 0,
          offsetY: 0,
          affectStroke: false,
          nonScaling: false,
        },
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: true,
        hasControls: true,
      },
    },
  },
  {
    thumbnail:
      "https://dzfvd4zd81.ufs.sh/f/ZgqgVp1atChfWOSblwp3aB6vRwlcjbdFJyuDGqm127LnkUHz",
    name: "flash sale",
    json: {
      version: "5.5.2",
      objects: [
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 175.5,
          top: -286.5,
          width: 900,
          height: 1200,
          fill: "rgba(255, 226, 226, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: {
            color: "rgba(0,0,0,0.8)",
            blur: 5,
            offsetX: 0,
            offsetY: 0,
            affectStroke: false,
            nonScaling: false,
          },
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          name: "clip",
          selectable: false,
          hasControls: false,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 319.33685515,
          top: 106.17690995,
          width: 315.5859375,
          height: 195.264,
          fill: "rgba(0,0,0,1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.00931204,
          scaleY: 2.00931204,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 700,
          fontSize: 80,
          text: "FLASH\nSALE",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 329.33685515,
          top: 116.17690995,
          width: 315.5859375,
          height: 195.264,
          fill: "rgba(249, 143, 135, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.00931204,
          scaleY: 2.00931204,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 700,
          fontSize: 80,
          text: "FLASH\nSALE",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 713.29149494,
          top: -569.85874859,
          width: 300,
          height: 300,
          fill: "rgba(249, 143, 135, 1)",
          stroke: "rgba(255, 255, 255, 1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.39243037,
          scaleY: 2.05575792,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -718.03385705,
          top: 1440.10608693,
          width: 300,
          height: 300,
          fill: "rgba(249, 143, 135, 1)",
          stroke: "rgba(255, 255, 255, 1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.39243037,
          scaleY: 2.05575792,
          angle: 310.75212427,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -618.1125382,
          top: 74.30990859,
          width: 300,
          height: 300,
          fill: "rgba(0, 0, 0, 0)",
          stroke: "rgba(218, 128, 128, 1)",
          strokeWidth: 7,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.39243037,
          scaleY: 2.05575792,
          angle: -49.24787573,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -659.81729654,
          top: 41.59728214,
          width: 300,
          height: 300,
          fill: "rgba(0, 0, 0, 0)",
          stroke: "rgba(218, 128, 128, 1)",
          strokeWidth: 7,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.39243037,
          scaleY: 2.05575792,
          angle: -49.24787573,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 536.13624411,
          top: 1302.74377896,
          width: 300,
          height: 300,
          fill: "rgba(0, 0, 0, 0)",
          stroke: "rgba(218, 128, 128, 1)",
          strokeWidth: 7,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.39243037,
          scaleY: 2.05575792,
          angle: -49.24787573,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 568.61657383,
          top: 1341.96820759,
          width: 300,
          height: 300,
          fill: "rgba(0, 0, 0, 0)",
          stroke: "rgba(218, 128, 128, 1)",
          strokeWidth: 7,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 4.39243037,
          scaleY: 2.05575792,
          angle: -49.24787573,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 451.17501325,
          top: 36.86030723,
          width: 382.89205307,
          height: 49.72,
          fill: "rgba(189, 114, 112, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Georgia",
          fontWeight: 500,
          fontSize: 44,
          text: "COMPANY, INC.",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 461.17501325,
          top: 536.93149494,
          width: 382.89205307,
          height: 49.72,
          fill: "rgba(189, 114, 112, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Georgia",
          fontWeight: 500,
          fontSize: 44,
          text: "SHOP NOW",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 493.65534296,
          top: 795.97604372,
          width: 382.89205307,
          height: 49.72,
          fill: "rgba(189, 114, 112, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 0.92095909,
          scaleY: 0.92095909,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Georgia",
          fontWeight: 500,
          fontSize: 44,
          text: "www.website.com",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.5.2",
        originX: "left",
        originY: "top",
        left: 175.5,
        top: -286.5,
        width: 900,
        height: 1200,
        fill: "rgba(255, 226, 226, 1)",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: {
          color: "rgba(0,0,0,0.8)",
          blur: 5,
          offsetX: 0,
          offsetY: 0,
          affectStroke: false,
          nonScaling: false,
        },
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: true,
        hasControls: true,
      },
    },
  },
  {
    thumbnail:
      "https://dzfvd4zd81.ufs.sh/f/ZgqgVp1atChfIq71dQPSP0sWkCDLOMeU4q7fVrawRd5uiTKJ",
    name: "travel",
    json: {
      version: "5.5.2",
      objects: [
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 175.5,
          top: -286.5,
          width: 900,
          height: 1200,
          fill: "white",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: {
            color: "rgba(0,0,0,0.8)",
            blur: 5,
            offsetX: 0,
            offsetY: 0,
            affectStroke: false,
            nonScaling: false,
          },
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          name: "clip",
          selectable: false,
          hasControls: false,
        },
        {
          type: "image",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -156.31547396,
          top: -290.49606594,
          width: 1080,
          height: 614,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.70156488,
          scaleY: 1.95439739,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          selectable: true,
          hasControls: true,
          src: "https://images.unsplash.com/photo-1518950957614-73ac0a001408?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1MjE5OTh8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTk0MzM0Nzl8&ixlib=rb-4.0.3&q=80&w=1080",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "rect",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 28.02322967,
          top: -306.45710004,
          width: 400,
          height: 400,
          fill: "rgba(0, 0, 0, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 2,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.075667,
          scaleY: 3.075667,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 0.45,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 281.43686774,
          top: 135.79130761,
          width: 300,
          height: 300,
          fill: "rgba(78, 145, 145, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.57267266,
          scaleY: 3.57267266,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 0.72,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 498.50034799,
          top: 314.0169935,
          width: 234.88867188,
          height: 50.85,
          fill: "rgba(254, 254, 254, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.74624017,
          scaleY: 1.74624017,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Brush Script MT",
          fontWeight: 500,
          fontSize: 45,
          text: "Its time to",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 432.66916448,
          top: 420.68139255,
          width: 271.12422089,
          height: 50.85,
          fill: "rgba(254, 254, 254, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.15484556,
          scaleY: 2.15484556,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 500,
          fontSize: 45,
          text: "TRAVEL 🏝️",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 401.19670288,
          top: 658.46712583,
          width: 402.74732486,
          height: 50.85,
          fill: "rgba(254, 254, 254, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.60484426,
          scaleY: 1.60484426,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Brush Script MT",
          fontWeight: 500,
          fontSize: 45,
          text: "Explore the island",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 586.96336093,
          top: 754.39814037,
          width: 234.88867188,
          height: 50.85,
          fill: "rgba(254, 254, 254, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.63590157,
          scaleY: 1.63590157,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 500,
          fontSize: 45,
          text: "25% off",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -513.12663919,
          top: 559.66167104,
          width: 300,
          height: 300,
          fill: "rgba(116, 211, 211, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.80344573,
          scaleY: 1.80344573,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "circle",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: -77.24053953,
          top: -667.99662795,
          width: 300,
          height: 300,
          fill: "rgba(78, 145, 145, 1)",
          stroke: "rgba(0,0,0,1)",
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 2.71131385,
          scaleY: 2.71131385,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 0.72,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          radius: 150,
          startAngle: 0,
          endAngle: 360,
          selectable: true,
          hasControls: true,
        },
        {
          type: "textbox",
          version: "5.5.2",
          originX: "left",
          originY: "top",
          left: 230.75492307,
          top: -176.28750966,
          width: 234.88867188,
          height: 109.836,
          fill: "rgba(254, 254, 254, 1)",
          stroke: null,
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1.4971626,
          scaleY: 1.4971626,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Arial Black",
          fontWeight: 500,
          fontSize: 45,
          text: "4 SPOTS LEFT",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          selectable: true,
          hasControls: true,
          editable: true,
        },
      ],
      clipPath: {
        type: "rect",
        version: "5.5.2",
        originX: "left",
        originY: "top",
        left: 175.5,
        top: -286.5,
        width: 900,
        height: 1200,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: {
          color: "rgba(0,0,0,0.8)",
          blur: 5,
          offsetX: 0,
          offsetY: 0,
          affectStroke: false,
          nonScaling: false,
        },
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: true,
        hasControls: true,
      },
    },
  },
];
