import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { CreateWorkspaceModal } from "@/modules/jira/features/workspaces/ui/components/create-workspace-modal";
import { EditTaskModal } from "@/modules/jira/features/tasks/ui/components/edit-task-modal";
import { MenuApps } from "@/components/menu-apps";
import { SlackSidebar } from "@/modules/slack/components/slack-sidebar";
import { CreateChannelModal } from "@/modules/slack/features/channels/ui/components/create-channel-modal";
import { EditChannelModal } from "@/modules/slack/features/channels/ui/components/edit-channel-modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "350px",
          } as React.CSSProperties
        }
      >
        <AppSidebar>
            <SlackSidebar />
        </AppSidebar>
        <SidebarInset>
          <header className="bg-background sticky top-0 flex shrink-0 items-center gap-2 border-b p-4">
            <SidebarTrigger className="-ml-1" />
            <Separator
              orientation="vertical"
              className="mr-2 data-[orientation=vertical]:h-4"
            />
            <div className="ml-auto">
              <MenuApps />
            </div>
          </header>
          <div className="flex flex-1 flex-col gap-4 p-4">{children}</div>
        </SidebarInset>
      </SidebarProvider>
      <CreateWorkspaceModal />
      <CreateChannelModal />
      <EditChannelModal />
      <EditTaskModal />
    </>
  );
}
